# Generated by Django 3.0.6 on 2022-07-19 13:10

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('model_garden', '0026_auto_20200914_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='local_image',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
